### ISSUE TITLE
Question regarding Fig.1 in paper

### ISSUE THREAD

**Issue by Irislucent** [juntang-zhuang/GSAM#9]
Thank you for presenting this excellent work.

I have a question about Fig. 1. It seems to me that the plots for w_1 and w_2 are not drawn with the same \rho. The reason f_p(w_1) < f_p(w_2) is that w_1 used a smaller \rho. If w_1 uses the same \rho as w_2 (which is wider), then f_p(w_1) should be much higher than f_p(w_2). Or my understanding could be wrong.

Thank you in advance.

**Comment by juntang-zhuang** [comment]
The figure is illustrative, not quantitative, but the argument is true. You can construct a quadratic case:

`f1(x) = a1 + b1 x^2, fp1(x)=a1+b1 (x+\rho)^2` only consider `x>0` due to symmetry
`f2(x) = a2 + b2 x^2, fp2(x)=a2 +b2 (x+\rho)^2`

You can tune the relative values of `a1, b1, a2, b2` and can construct cases where `fp1(x)<fp(2)`or `fp1(x)>fp2(x)` within a bounded region of `x` (e.g. `-1<x<1`). Due to the flexibility in construction here, you can not faithfully say which one is better just from `fp1(x)` and `fp2(x)`
